// lib/api/daily-challenge.ts — Thử thách ngày (FT-34)

import { request } from "./client";

// ── DTOs ──────────────────────────────────────────────────────────────────────

export type DailyChallengeStatus = "Scheduled" | "Active" | "Closed";

export interface DailyChallengeDto {
  id: string;
  challengeDate: string; // "yyyy-MM-dd"
  status: DailyChallengeStatus;
  tutorialId: string;
  tutorialTitle: string;
  tutorialSlug: string;
  tutorialCoverImageUrl: string | null;
  tutorialDifficulty: "Beginner" | "Intermediate" | "Advanced" | string;
  tutorialAuthorId: string;
  tutorialAuthorName: string | null;
  isAutoGenerated: boolean;
  submissionCount: number;
  // null khi chưa đăng nhập (backend không tính được các field cá nhân hoá)
  hasSubmittedToday: boolean | null;
  myChallengeStreak: number | null;
  createdAt: string;
}

export interface DailyChallengeSubmissionDto {
  id: string;
  userId: string;
  userDisplayName: string | null;
  userAvatarUrl: string | null;
  photoUrl: string;
  note: string | null;
  likeCount: number;
  isLikedByCurrentUser: boolean;
  finalRank: number | null;
  createdAt: string;
}

export interface ChallengeLeaderboardEntryDto {
  rank: number;
  userId: string;
  displayName: string | null;
  avatarUrl: string | null;
  currentStreak: number;
  longestStreak: number;
}

export interface ChallengeSuggestionDto {
  tutorialId: string;
  title: string;
  slug: string;
  coverImageUrl: string | null;
  difficulty: string;
  categoryId: number;
  achievementCount: number;
}

export interface AdminChallengeCalendarItemDto {
  id: string;
  challengeDate: string;
  status: DailyChallengeStatus;
  tutorialId: string;
  tutorialTitle: string;
  isAutoGenerated: boolean;
  createdByUserId: string | null;
}

export interface PagedResult<T> {
  items: T[];
  totalCount: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface SubmitDailyChallengeRequest {
  photoUrl: string;
  note?: string | null;
}

export interface ScheduleDailyChallengeRequest {
  challengeDate: string; // "yyyy-MM-dd"
  tutorialId: string;
}

export interface ToggleLikeResponse {
  isLiked: boolean;
}

// ── Daily Challenge API ─────────────────────────────────────────────────────

export const dailyChallengeApi = {
  /** GET /api/daily-challenge/today — public, cá nhân hoá nếu có token */
  getToday(token?: string): Promise<DailyChallengeDto> {
    return request<DailyChallengeDto>("/api/daily-challenge/today", { token });
  },

  /** GET /api/daily-challenge/today/submissions — sắp xếp theo lượt thích */
  getTodaySubmissions(
    params?: { page?: number; pageSize?: number },
    token?: string
  ): Promise<PagedResult<DailyChallengeSubmissionDto>> {
    const q = new URLSearchParams();
    if (params?.page) q.set("page", String(params.page));
    if (params?.pageSize) q.set("pageSize", String(params.pageSize));
    const qs = q.toString() ? `?${q.toString()}` : "";
    return request<PagedResult<DailyChallengeSubmissionDto>>(
      `/api/daily-challenge/today/submissions${qs}`,
      { token }
    );
  },

  /** POST /api/daily-challenge/today/submit — cần đăng nhập */
  submit(token: string, body: SubmitDailyChallengeRequest): Promise<DailyChallengeSubmissionDto> {
    return request<DailyChallengeSubmissionDto>("/api/daily-challenge/today/submit", {
      method: "POST",
      body: JSON.stringify(body),
      token,
    });
  },

  /** GET /api/daily-challenge/leaderboard — top Chuỗi thử thách */
  getLeaderboard(top = 20): Promise<ChallengeLeaderboardEntryDto[]> {
    return request<ChallengeLeaderboardEntryDto[]>(`/api/daily-challenge/leaderboard?top=${top}`);
  },

  /** POST /api/likes/toggle — like/unlike một bài nộp thử thách (cần đăng nhập) */
  toggleSubmissionLike(token: string, submissionId: string): Promise<ToggleLikeResponse> {
    // Dùng PascalCase key vì backend dùng C# positional record (TargetId, TargetType)
    return request<ToggleLikeResponse>("/api/likes/toggle", {
      method: "POST",
      body: JSON.stringify({ TargetId: submissionId, TargetType: "DailyChallengeSubmission" }),
      token,
    });
  },

  // ── Admin/Manager ────────────────────────────────────────────────────────

  /** GET /api/daily-challenge/admin/suggestions — gợi ý tutorial để đặt lịch, không ghi DB */
  adminGetSuggestions(token: string, count = 5): Promise<ChallengeSuggestionDto[]> {
    return request<ChallengeSuggestionDto[]>(
      `/api/daily-challenge/admin/suggestions?count=${count}`,
      { token }
    );
  },

  /** POST /api/daily-challenge/admin/schedule — đặt lịch tutorial cho 1 ngày (hôm nay hoặc tương lai) */
  adminSchedule(token: string, body: ScheduleDailyChallengeRequest): Promise<DailyChallengeDto> {
    return request<DailyChallengeDto>("/api/daily-challenge/admin/schedule", {
      method: "POST",
      body: JSON.stringify(body),
      token,
    });
  },

  /** GET /api/daily-challenge/admin/calendar — danh sách lịch trong khoảng ngày */
  adminGetCalendar(
    token: string,
    params?: { fromDate?: string; toDate?: string; page?: number; pageSize?: number }
  ): Promise<PagedResult<AdminChallengeCalendarItemDto>> {
    const q = new URLSearchParams();
    if (params?.fromDate) q.set("fromDate", params.fromDate);
    if (params?.toDate) q.set("toDate", params.toDate);
    if (params?.page) q.set("page", String(params.page));
    if (params?.pageSize) q.set("pageSize", String(params.pageSize));
    const qs = q.toString() ? `?${q.toString()}` : "";
    return request<PagedResult<AdminChallengeCalendarItemDto>>(
      `/api/daily-challenge/admin/calendar${qs}`,
      { token }
    );
  },

  /** POST /api/daily-challenge/admin/run-scheduler — chạy tay job 00:00 GMT+7 (đóng hôm qua + kích hoạt hôm nay), dùng để test/khắc phục */
  adminRunScheduler(token: string): Promise<{ message: string }> {
    return request<{ message: string }>("/api/daily-challenge/admin/run-scheduler", {
      method: "POST",
      token,
    });
  },
};
