// lib/api/weekly-challenge.ts — Thử thách tuần (mirror daily-challenge.ts; chỉ mở Chủ Nhật)

import { request } from "./client";
import { PagedResult } from "./daily-challenge";

// ── DTOs ──────────────────────────────────────────────────────────────────────

export type WeeklyChallengeStatus = "Scheduled" | "Active" | "Closed";

export interface WeeklyChallengeDto {
  id: string;
  challengeDate: string; // "yyyy-MM-dd" — luôn là một Chủ Nhật
  status: WeeklyChallengeStatus;
  tutorialId: string;
  tutorialTitle: string;
  tutorialSlug: string;
  tutorialCoverImageUrl: string | null;
  tutorialDifficulty: "Beginner" | "Intermediate" | "Advanced" | string;
  tutorialAuthorId: string;
  tutorialAuthorName: string | null;
  isAutoGenerated: boolean;
  submissionCount: number;
  // null khi chưa đăng nhập (backend không tính được các field cá nhân hoá)
  hasSubmittedThisWeek: boolean | null;
  myChallengeStreak: number | null;
  createdAt: string;
}

export interface WeeklyChallengeSubmissionDto {
  id: string;
  userId: string;
  userDisplayName: string | null;
  userAvatarUrl: string | null;
  photoUrl: string;
  note: string | null;
  likeCount: number;
  isLikedByCurrentUser: boolean;
  finalRank: number | null;
  createdAt: string;
}

export interface WeeklyChallengeSuggestionDto {
  tutorialId: string;
  title: string;
  slug: string;
  coverImageUrl: string | null;
  difficulty: string;
  categoryId: number;
  achievementCount: number;
}

export interface AdminWeeklyChallengeCalendarItemDto {
  id: string;
  challengeDate: string;
  status: WeeklyChallengeStatus;
  tutorialId: string;
  tutorialTitle: string;
  isAutoGenerated: boolean;
  createdByUserId: string | null;
}

export interface SubmitWeeklyChallengeRequest {
  photoUrl: string;
  note?: string | null;
}

export interface ScheduleWeeklyChallengeRequest {
  challengeDate: string; // "yyyy-MM-dd" — phải là Chủ Nhật
  tutorialId: string;
}

// ── Weekly Challenge API ────────────────────────────────────────────────────

export const weeklyChallengeApi = {
  /** GET /api/weekly-challenge/current — công khai, cá nhân hoá nếu có token. Chỉ có dữ liệu vào Chủ Nhật. */
  getCurrent(token?: string): Promise<WeeklyChallengeDto> {
    return request<WeeklyChallengeDto>("/api/weekly-challenge/current", {
      token,
      expectedErrorStatuses: [404],
    });
  },

  /** GET /api/weekly-challenge/current/submissions — sắp xếp theo lượt thích */
  getCurrentSubmissions(
    params?: { page?: number; pageSize?: number },
    token?: string
  ): Promise<PagedResult<WeeklyChallengeSubmissionDto>> {
    const q = new URLSearchParams();
    if (params?.page) q.set("page", String(params.page));
    if (params?.pageSize) q.set("pageSize", String(params.pageSize));
    const qs = q.toString() ? `?${q.toString()}` : "";
    return request<PagedResult<WeeklyChallengeSubmissionDto>>(
      `/api/weekly-challenge/current/submissions${qs}`,
      { token }
    );
  },

  /** POST /api/weekly-challenge/current/submit — cần đăng nhập */
  submit(token: string, body: SubmitWeeklyChallengeRequest): Promise<WeeklyChallengeSubmissionDto> {
    return request<WeeklyChallengeSubmissionDto>("/api/weekly-challenge/current/submit", {
      method: "POST",
      body: JSON.stringify(body),
      token,
    });
  },

  /** POST /api/likes/toggle — like/unlike một bài nộp thử thách tuần (cần đăng nhập) */
  toggleSubmissionLike(token: string, submissionId: string): Promise<{ isLiked: boolean }> {
    return request<{ isLiked: boolean }>("/api/likes/toggle", {
      method: "POST",
      body: JSON.stringify({ targetId: submissionId, targetType: "WeeklyChallengeSubmission" }),
      token,
    });
  },

  // ── Admin/Manager ────────────────────────────────────────────────────────

  /** GET /api/weekly-challenge/admin/suggestions — gợi ý tutorial Advanced để đặt lịch, không ghi DB */
  adminGetSuggestions(token: string, count = 5): Promise<WeeklyChallengeSuggestionDto[]> {
    return request<WeeklyChallengeSuggestionDto[]>(
      `/api/weekly-challenge/admin/suggestions?count=${count}`,
      { token }
    );
  },

  /** POST /api/weekly-challenge/admin/schedule — đặt lịch tutorial cho một Chủ Nhật (hôm nay hoặc tương lai) */
  adminSchedule(token: string, body: ScheduleWeeklyChallengeRequest): Promise<WeeklyChallengeDto> {
    return request<WeeklyChallengeDto>("/api/weekly-challenge/admin/schedule", {
      method: "POST",
      body: JSON.stringify(body),
      token,
    });
  },

  /** GET /api/weekly-challenge/admin/calendar — danh sách lịch trong khoảng ngày */
  adminGetCalendar(
    token: string,
    params?: { fromDate?: string; toDate?: string; page?: number; pageSize?: number }
  ): Promise<PagedResult<AdminWeeklyChallengeCalendarItemDto>> {
    const q = new URLSearchParams();
    if (params?.fromDate) q.set("fromDate", params.fromDate);
    if (params?.toDate) q.set("toDate", params.toDate);
    if (params?.page) q.set("page", String(params.page));
    if (params?.pageSize) q.set("pageSize", String(params.pageSize));
    const qs = q.toString() ? `?${q.toString()}` : "";
    return request<PagedResult<AdminWeeklyChallengeCalendarItemDto>>(
      `/api/weekly-challenge/admin/calendar${qs}`,
      { token }
    );
  },

  /** POST /api/weekly-challenge/admin/run-scheduler — chạy tay job 00:00 GMT+7 (đóng tuần trước + kích hoạt tuần này nếu là Chủ Nhật), dùng để test/khắc phục */
  adminRunScheduler(token: string): Promise<{ message: string }> {
    return request<{ message: string }>("/api/weekly-challenge/admin/run-scheduler", {
      method: "POST",
      token,
    });
  },
};
